In [1]:
pass

In [14]:
with open("input-2.txt") as f:
    data = f.read()

In [15]:
lines = data.split("\n")[:-1]

In [16]:
lines[0]

'29x13x26'

In [21]:
dims = np.array([[int(i) for i in j.split("x")] for j in lines])

In [19]:
import numpy as np

In [22]:
dims.drop(1,axis=1)

AttributeError: 'numpy.ndarray' object has no attribute 'drop'

In [23]:
dims

array([[29, 13, 26],
       [11, 11, 14],
       [27,  2,  5],
       ...,
       [ 3,  2, 22],
       [14,  3,  5],
       [10,  9,  8]])

In [28]:
dims[:,:2].prod(axis=1)

array([377, 121,  54,  60, 285, 754, 184, 136, 560, 276, 187, 437,  50,
        15, 350, 230, 551, 170, 780, 112,  35, 184,  40,  72,  60,  84,
       230, 841,  21, 220, 120, 260,  24,  32, 486,  72, 306, 350, 450,
       306, 644, 180,  98, 667, 120, 132,  15,  70, 672, 391,  60, 184,
        90, 414,  17, 299,  36, 484, 220, 812, 462, 112, 360,  56,  90,
        12, 450, 112,  12, 144, 560, 672,  72, 414,  88, 450,  84,  66,
        12,  18, 187, 600, 189, 104,  58, 456, 529, 728,  72, 750, 551,
        48, 725, 342, 294, 247, 190,  36, 108, 600, 108,  45, 510, 342,
        99, 224,  33, 476, 432, 132, 114, 112, 616, 377, 144, 812, 180,
       209, 728, 391,  25,  17, 459, 364, 182, 319, 638,  78, 414, 175,
       162, 231, 308, 325, 551, 464, 210, 175,  45,  15, 216, 138, 484,
       120, 650, 190, 600, 150, 170, 420, 136, 126,  15, 408, 280, 594,
       252, 207, 336, 126,  27, 130,  60, 460, 176, 812, 208, 189, 182,
       299, 133, 207, 189, 189, 580, 299, 475, 132, 420, 126, 62

In [41]:
sides = np.stack([dims[:,:2],dims[:,::2], dims[:,-2:]])

In [42]:
sides.shape

(3, 1000, 2)

In [43]:
side_area = sides.prod(axis=2)
side_area

array([[377, 121,  54, ...,   6,  42,  90],
       [754, 154, 135, ...,  66,  70,  80],
       [338, 154,  10, ...,  44,  15,  72]])

In [44]:
side_area.min(axis=0).sum() + 2 * side_area.sum()

1586300

In [45]:
side_per = 2 * sides.sum(axis=2)
side_per

array([[ 84,  44,  58, ...,  10,  34,  38],
       [110,  50,  64, ...,  50,  38,  36],
       [ 78,  50,  14, ...,  48,  16,  34]])

In [47]:
side_per.min(axis=0).sum() + dims.prod(axis=1).sum()

3737498